version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "standardjs"