name: 'Build with Maven'

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: 'Build on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: 'x64'

      - name: 'Build project with Maven'
        run: mvn verify